name: gmediarender
version: 0
summary: Small headless uPNP media renderer.
description: |
  gmediarender is a UPnP media renderer for POSIX-compliant
  systems, such as Linux or UNIX. It implements the server
  component that provides UPnP controllers a means to render media
  content (audio, video and images) from a UPnP media server.
  
  gmrender-resurrect is a fork from GMediaRender which was abandonded upstream.
  
  This snap is built from the Ubuntu 16.04 repository packages.

confinement: devmode

apps:
  gmediarender:
    command: run-gmediarender
    plugs:
      - pulseaudio
      - network
      - network-bind

parts:
  gmediarender:
    plugin: nil
    stage-packages:
      - gmediarender
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
  copy:
    plugin: copy
    files:
      run-gmediarender: run-gmediarender
